# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Encoder": "Encoder-with-NodeMatching.ipynb",
         "MoCo": "MoCo.ipynb",
         "concat_all_gather": "MoCo.ipynb",
         "SceneGraph": "Scene-graph.ipynb",
         "setup_tb": "train_model.ipynb",
         "run_training": "train_model.ipynb",
         "train": "train_model.ipynb",
         "val_retrieval": "train_model.ipynb"}

modules = ["model/encoder.py",
           "model/model.py",
           "model/scene_graph/scene_graph.py",
           "trainer.py"]

doc_url = "https://sakshamjindal.github.io/core/"

git_url = "https://github.com/sakshamjindal/core/tree/master/"

def custom_doc_links(name): return None
