# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Encoder": "Encoder.ipynb",
         "MoCo": "MoCo.ipynb",
         "concat_all_gather": "MoCo.ipynb",
         "Model": "Model.ipynb",
         "SceneGraph": "Scene-graph.ipynb"}

modules = ["model/encoder.py",
           "model/model.py",
           "model/main.py",
           "scene_graph/scene_graph.py"]

doc_url = "https://sakshamjindal.github.io/core/"

git_url = "https://github.com/sakshamjindal/core/tree/master/"

def custom_doc_links(name): return None
